### PR TITLE
build: Add CMake definition file

### LINKED ISSUE #21: CMake?
I saw your video at FOSDEM and am really excited about the project! Had a question...

There are Makefiles, which is great. Would you be open to adding a [CMake](https://cmake.org/) definition file to ease compilation? For builds using cmake, it would make it a lot easier to embed gfxprim within another project, and save from having to build the `config.h` with `./configure`.

### PR DESCRIPTION
**Pull request by RobLoach**
This is potentially what a CMake definition file could look like. It detects what libraries are available, and adds them as defines when compiling. You can selectively disable the features as you wish too.

There still needs a way to detect if the .gen.h/c files haven't been built, and construct them.

Fixes #21

### CODE REVIEW

**Comment by metan-ucw** [comment]
We just need cmake equivalent for pattern rules for the gen.c and gen.h files. In make it's quite simple I would be surprised if equivalent functionality wasn't implemented in cmake.

**Comment by metan-ucw** [comment]
I've googled a bit and it seems that we are supposed to loop over the input files, i.e. *.gen.*.t and call add_custom_command() for each of them.

https://cmake.org/pipermail/cmake/2010-June/037733.html

**Comment by metan-ucw** [comment]
Any progress on this or should I close the issue?

**Comment by RobLoach** [comment]
Let's close it. While it would be nice, I had some troubles getting the python to run.

**Pull request closed without merging**
